<div class="converter">
    <h2>Конвертор валют</h2>
    <form action="">
        <h3>З якої валюти: </h3>
        <select name="" id="">
            <option value="dollar">Долар</option>
            <option value="euro">Євро</option>
            <option value="rouble">Рубль</option>
            <option value="grivnia">Гривня</option>
        </select><br>
        <h3>Сума: </h3>
        <input type="number"><br><hr>
        <h3>В яку валюту: </h3>
        <select name="" id="">
            <option value="dollar">Долар</option>
            <option value="euro">Євро</option>
            <option value="rouble">Рубль</option>
            <option value="grivnia">Гривня</option>
        </select><br>
        <input type="submit" value="Розрахувати">
    </form>

</div>
