<?php
/** @var $block \Smile\Customer\Block\VisitedUrls */
?>

<table>
    <tr>
    <td><?php echo __('Customer id')?></td>
    <td><?php echo __('Customer Full Name')?></td>
    <td><?php echo __('Visited url')?></td>
    <td><?php echo __('Is active')?></td>
    </tr>
    <?php foreach ($block->getCustomerUrls()->getItems() as $item): ?>
    <tr>
        <td><?php echo $item->getCustomerId() ?></td>
        <td><?php echo __('%1 %2', $item->getFirstname(), $item->getLastname()); ?></td>
        <td>
            <a href="<?php echo rtrim($block->getUrl(trim($item->getVisitedUrl(), '/')), '/'); ?>"><?php echo $item->getVisitedUrl(); ?></a>
        </td>
        <td><?php echo ($item->isActive() ? 'Enabled' : 'Disabled'); ?></td>
    </tr>
    <?php endforeach; ?>
</table>
