<?php
/* @var \AlexDbModules\CustomerFeedback\Block\FeedbackForm $block */
?>
<h2>Fill in the form for sending us a feedback:</h2>

<form action="<?= $block->getFormAction(); ?>" method="post">
    <div>
        <label for="customer_name">Enter your name: </label>
        <input type="text" name="customer_name" id="customer_name">
    </div>
    <br>
    <div>
        <label for="email">Enter your email: </label>
        <input type="text" name="email" id="email">
    </div>
    <br>
    <div>
        <label for="customer_message">Enter your message: </label>
        <textarea type="text" name="customer_message" id="customer_message" rows="5"></textarea>
    </div>
    <br>
    <div>
        <input type="submit" name="send_feedback" value="Send feedback">
    </div>

</form>
