<h2>Варіанти: </h2>
<form action="#">
    <input type="radio" name="subs" value="general-subscription">
    <label for="general-subscription">Загальна підписка</label>
    <br><br>
    <input type="radio" name="subs" value="important-subscription">
    <label for="important-subscription">Підписка тільки з важливими повідомленнями</label>
    <br><br>
    <input type="submit" value="Активувати підписку">
</form>
